markdown: redcarpet
highlighter: pygments
permalink: blog/:year/:month/:day/:title.html
paginate: 5
paginate_path: page/:num
encoding: "utf-8"
future: true
lsi: false
safe: true

redcarpet:
    extensions:
        - with_toc_data
        - hard_wrap
        - no_intra_emphasis
        - tables
        - fenced_code_blocks
        - autolink

blog:
    name: The Pursuit of Happyness # 博客名称
    description: Dream come true # 博客描述
    title: 钟爱一生的博客 # 网页标题
    url: http://blog.sina.com.cn/y2kking # 博客地址
    duoshuo: 海天心Y2kking  # 多说ID
    tongji: 8d30b14c805aa6477e40b3b82084d201 # 百度统计ID
    qiniu: # 七牛云地址
author:
    name: 钟爱一生 # 作者名称
    email: liangqingyu123@foxmail.com # 邮箱地址
    weibo: http://weibo.com/1419491963  # 微博地址
    github: yusmile.github.io  # GitHub地址
    logo: /res/img/icon2.png # logo地址
    douban:
        name:    # 豆瓣地址名称
        key:           # 豆瓣API Key
