markdown: redcarpet
highlighter: pygments
permalink: blog/:year/:month/:day/:title.html
paginate: 5
paginate_path: page/:num
encoding: "utf-8"
future: true
lsi: false
safe: true

redcarpet:
    extensions:
        - with_toc_data
        - hard_wrap
        - no_intra_emphasis
        - tables
        - fenced_code_blocks
        - autolink

blog:
    name: LiangQingYu Blog # 博客名称
    description: Just do it # 博客描述
    title: 梁擎宇的博客 # 网页标题
    url: qingyu1229.github.io # 博客地址
    duoshuo:  # 多说ID
    tongji: 339c3dde0596b995600e5fed42918ad8 # 百度统计ID
    qiniu: # 七牛云地址
author:
    name: 梁擎宇 # 作者名称
    email: liangqingyu123@foxmail.com # 邮箱地址
    weibo: http://weibo.com/u/1811088830  # 微博地址
    github: https://github.com/qingyu1229  # GitHub地址
    logo: /res/img/icon2.png # logo地址
    douban:
        name:    # 豆瓣地址名称
        key:           # 豆瓣API Key
